In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import re, os

In [4]:
data = pd.read_excel("Dataset_complet_Meteo.xlsx")

In [5]:
data.head()

,id,time,weather_code,temperature_2m_max,temperature_2m_min,temperature_2m_mean,apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,sunrise,...,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,shortwave_radiation_sum,et0_fao_evapotranspiration,city,region,latitude,longitude
0,1,2020-01-01,3,33.2,2026-09-21 00:00:00,2026-05-26 00:00:00,34.0,2026-06-25 00:00:00,2026-01-29 00:00:00,2020-01-01 06:22:00,...,0.0,2026-05-10 00:00:00,2026-05-24 00:00:00,132,20.18,4.59,Bafia,Centre,4.75,11.23
1,2,2020-01-02,3,31.9,2026-09-21 00:00:00,2026-09-25 00:00:00,2026-01-31 00:00:00,2026-03-23 00:00:00,27.0,2020-01-02 06:23:00,...,0.0,2026-05-08 00:00:00,2026-06-25 00:00:00,77,19.39,4.64,Bafia,Centre,4.75,11.23
2,3,2020-01-03,3,32.0,2026-03-19 00:00:00,25.0,2026-07-31 00:00:00,2026-02-19 00:00:00,2026-01-25 00:00:00,2020-01-03 06:23:00,...,0.0,2026-09-08 00:00:00,2026-09-25 00:00:00,65,2026-03-20 00:00:00,4.78,Bafia,Centre,4.75,11.23
3,4,2020-01-04,3,2026-05-31 00:00:00,2026-01-19 00:00:00,2026-07-24 00:00:00,32.3,2026-07-20 00:00:00,2026-04-25 00:00:00,2020-01-04 06:24:00,...,0.0,2026-02-11 00:00:00,2026-02-20 00:00:00,106,20.48,4.59,Bafia,Centre,4.75,11.23
4,5,2020-01-05,3,31.9,2026-03-19 00:00:00,2026-08-24 00:00:00,33.1,2026-03-20 00:00:00,2026-09-25 00:00:00,2020-01-05 06:24:00,...,0.0,2026-03-11 00:00:00,2026-08-23 00:00:00,100,19.98,4.39,Bafia,Centre,4.75,11.23

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87240 entries, 0 to 87239
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           87240 non-null  int64
 1   time                         87240 non-null  datetime64[ns]
 2   weather_code                 87240 non-null  int64
 3   temperature_2m_max           87240 non-null  object
 4   temperature_2m_min           87240 non-null  object
 5   temperature_2m_mean          87240 non-null  object
 6   apparent_temperature_max     87240 non-null  object
 7   apparent_temperature_min     87240 non-null  object
 8   apparent_temperature_mean    87240 non-null  object
 9   sunrise                      87240 non-null  datetime64[ns]
 10  sunset                       87240 non-null  datetime64[ns]
 11  daylight_duration            87240 non-null  float64
 12  sunshine_duration            87240 non-null  object
 13  precipitation_sum            87240 non-null  object
 14  rain_sum                     87240 non-null  object
 15  snowfall_sum                 87240 non-null  float64
 16  precipitation_hours          87240 non-null  float64
 17  wind_speed_10m_max           87240 non-null  object
 18  wind_gusts_10m_max           87240 non-null  object
 19  wind_direction_10m_dominant  87240 non-null  int64
 20  shortwave_radiation_sum      87240 non-null  object
 21  et0_fao_evapotranspiration   87240 non-null  object
 22  city                         87240 non-null  object
 23  region                       87240 non-null  object
 24  latitude                     87240 non-null  object
 25  longitude                    87240 non-null  object
dtypes: datetime64[ns](3), float64(3), int64(3), object(17)
memory usage: 17.3+ MB

In [7]:
data.describe()

,id,time,weather_code,sunrise,sunset,daylight_duration,snowfall_sum,precipitation_hours,wind_direction_10m_dominant
count,87240.00000,87240,87240.000000,87240,87240,87240.000000,87240.0,87240.000000,87240.000000
mean,2617.70000,2022-12-26 00:00:00.000000256,40.556385,2022-12-26 06:08:23.672626944,2022-12-26 18:15:49.028885760,43645.372588,0.0,5.879184,185.365326
min,1.00000,2020-01-01 00:00:00,0.000000,2020-01-01 06:05:00,2020-01-01 17:45:00,41097.380000,0.0,0.000000,0.000000
25%,1148.00000,2021-06-29 00:00:00,3.000000,2021-06-29 05:52:45,2021-06-29 18:25:45,42970.900000,0.0,0.000000,108.000000
50%,2318.00000,2022-12-26 00:00:00,51.000000,2022-12-26 06:19:00,2022-12-26 18:11:00,43640.315000,0.0,4.000000,210.000000
75%,3681.00000,2024-06-23 00:00:00,61.000000,2024-06-23 06:09:00,2024-06-23 18:34:00,44318.552500,0.0,10.000000,260.000000
max,8724.00000,2025-12-20 00:00:00,65.000000,2025-12-20 06:26:00,2025-12-20 18:17:00,46198.170000,0.0,24.000000,360.000000
std,1880.39875,NaN,25.739631,NaN,NaN,912.377029,0.0,6.052920,95.195610

In [8]:
data.columns

Index(['id', 'time', 'weather_code', 'temperature_2m_max',
       'temperature_2m_min', 'temperature_2m_mean', 'apparent_temperature_max',
       'apparent_temperature_min', 'apparent_temperature_mean', 'sunrise',
       'sunset', 'daylight_duration', 'sunshine_duration', 'precipitation_sum',
       'rain_sum', 'snowfall_sum', 'precipitation_hours', 'wind_speed_10m_max',
       'wind_gusts_10m_max', 'wind_direction_10m_dominant',
       'shortwave_radiation_sum', 'et0_fao_evapotranspiration', 'city',
       'region', 'latitude', 'longitude'],
      dtype='object')

In [11]:
data["id"].nunique()

8724

In [12]:
data.shape

(87240, 26)

In [14]:
data.isnull().sum()

id                             0
time                           0
weather_code                   0
temperature_2m_max             0
temperature_2m_min             0
temperature_2m_mean            0
apparent_temperature_max       0
apparent_temperature_min       0
apparent_temperature_mean      0
sunrise                        0
sunset                         0
daylight_duration              0
sunshine_duration              0
precipitation_sum              0
rain_sum                       0
snowfall_sum                   0
precipitation_hours            0
wind_speed_10m_max             0
wind_gusts_10m_max             0
wind_direction_10m_dominant    0
shortwave_radiation_sum        0
et0_fao_evapotranspiration     0
city                           0
region                         0
latitude                       0
longitude                      0
dtype: int64

In [16]:
data["time"].max(), data["time"].mean(), data["time"].min()

(Timestamp('2025-12-20 00:00:00'),
 Timestamp('2022-12-26 00:00:00.000000256'),
 Timestamp('2020-01-01 00:00:00'))

In [17]:
data["time"].nunique()

2181

In [18]:
data["time"].value_counts()

time
2020-01-01    40
2020-01-02    40
2020-01-03    40
2020-01-04    40
2020-01-05    40
              ..
2025-12-16    40
2025-12-17    40
2025-12-18    40
2025-12-19    40
2025-12-20    40
Name: count, Length: 2181, dtype: int64

In [19]:
data["time"].value_counts().to_excel("temps.xlsx")

In [20]:
data.columns

Index(['id', 'time', 'weather_code', 'temperature_2m_max',
       'temperature_2m_min', 'temperature_2m_mean', 'apparent_temperature_max',
       'apparent_temperature_min', 'apparent_temperature_mean', 'sunrise',
       'sunset', 'daylight_duration', 'sunshine_duration', 'precipitation_sum',
       'rain_sum', 'snowfall_sum', 'precipitation_hours', 'wind_speed_10m_max',
       'wind_gusts_10m_max', 'wind_direction_10m_dominant',
       'shortwave_radiation_sum', 'et0_fao_evapotranspiration', 'city',
       'region', 'latitude', 'longitude'],
      dtype='object')

In [21]:
data['sunset'].nunique()

46448

In [22]:
data['latitude'].nunique()

39

In [23]:
data['longitude'].nunique()

39